# Writes every shader file under ROOT (src/*/shaders) into OUT as the table
# wxl::forever::shaders::kEmbeddedFiles, and copies the files to DEPLOY/Shaders/Forever/src when
# DEPLOY is set. Run with cmake -P from shared.cmake.

file(GLOB_RECURSE files RELATIVE "${ROOT}" "${ROOT}/*/shaders/*.hlsl" "${ROOT}/*/shaders/*.hlsli")
list(SORT files)

set(text "// Generated by cmake/EmbedShaders.cmake from src/*/shaders; do not edit.\n")
string(APPEND text "#include \"${ROOT}/core/ShaderLibrary.hpp\"\n\n")
string(APPEND text "namespace wxl::forever::shaders\n{\n    const EmbeddedFile kEmbeddedFiles[] = {\n")

set(count 0)
foreach(rel IN LISTS files)
    file(READ "${ROOT}/${rel}" body)
    string(APPEND text "        { \"${rel}\",\n")
    # MSVC caps one literal at about 16 KB; adjacent raw literals are joined by the compiler.
    string(LENGTH "${body}" len)
    set(pos 0)
    while(pos LESS len)
        string(SUBSTRING "${body}" ${pos} 8000 chunk)
        string(APPEND text "          R\"wxlhlsl(${chunk})wxlhlsl\"\n")
        math(EXPR pos "${pos} + 8000")
    endwhile()
    if(len EQUAL 0)
        string(APPEND text "          \"\"\n")
    endif()
    string(APPEND text "        },\n")
    math(EXPR count "${count} + 1")

    if(DEPLOY)
        get_filename_component(dir "${rel}" DIRECTORY)
        file(MAKE_DIRECTORY "${DEPLOY}/Shaders/Forever/src/${dir}")
        configure_file("${ROOT}/${rel}" "${DEPLOY}/Shaders/Forever/src/${rel}" COPYONLY)
    endif()
endforeach()

string(APPEND text "    };\n    const int kEmbeddedFileCount = ${count};\n}\n")
file(WRITE "${OUT}" "${text}")
