# wxl-graphics-lights: compiles the compute shaders (shaders/compute/<name>.cs.hlsl) to SPIR-V with DXC and
# writes them, with the D3D9 shaders' sources and the includes those read, into OUT (src/gpu/Shaders.gen.cpp,
# the implementation of src/gpu/Shaders.hpp). Run with cmake -P from shared.cmake:
#   DXC     the DirectX Shader Compiler executable
#   SRC     the shaders folder (holding compute/, d3d9/ and wxl/)
#   OUT     the generated .cpp (committed: a build without DXC uses it as is)
#   WORK    scratch folder for the .spv files (optional)
#   GFX     wxl-graphics-extend's shaders folder (its wxl/gfx includes)
#   SHADOW  wxl-graphics-shadow's shaders folder; the point-shadow variants compile only when it holds
#           wxl/shadow/shadow.hlsli (otherwise they are left empty and the runtime uses the plain ones)
# OUT is rewritten only when its content changed; a shader that fails to compile fails the build.

if(NOT DXC OR NOT SRC OR NOT OUT)
    message(FATAL_ERROR "CompileShaders.cmake: DXC, SRC and OUT are required")
endif()
if(NOT WORK)
    set(WORK "${CMAKE_CURRENT_BINARY_DIR}/wxl-graphics-lights-shaders")
endif()
file(MAKE_DIRECTORY "${WORK}")

set(have_shadow FALSE)
if(SHADOW AND EXISTS "${SHADOW}/wxl/shadow/shadow.hlsli")
    set(have_shadow TRUE)
endif()

# The pipelines in the order of LIGHTS_PIPE_* (shaders/compute/shared.h): name, source, defines.
# A "shadow" entry needs wxl-graphics-shadow's include.
set(pipes
    "surface|surface|"
    "field|field|"
    "field.shadow|field|shadow"
    "halo|halo|")

set(text "// Generated by cmake/CompileShaders.cmake from shaders/ (DXC, cs_6_0, -spirv, Vulkan 1.3); do not edit.\n")
string(APPEND text "#include \"Shaders.hpp\"\n\n")
string(APPEND text "namespace wxl::gfx::lights::shaders\n{\n    namespace\n    {\n")

set(modules "")
foreach(entry IN LISTS pipes)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 name)
    list(GET parts 1 source)
    list(LENGTH parts nparts)
    set(kind "")
    if(nparts GREATER 2)
        list(GET parts 2 kind)
    endif()
    string(REPLACE "." "_" ident "${name}")
    set(hlsl "${SRC}/compute/${source}.cs.hlsl")
    if(NOT EXISTS "${hlsl}")
        message(STATUS "CompileShaders.cmake: ${hlsl} is missing; lights.${name} stays empty")
        string(APPEND modules "            { nullptr, 0, \"lights.${name}\" },\n")
        continue()
    endif()
    if(kind STREQUAL "shadow" AND NOT have_shadow)
        string(APPEND text "        // shaders/compute/${source}.cs.hlsl with point shadows: wxl-graphics-shadow's include was absent\n")
        string(APPEND modules "            { nullptr, 0, \"lights.${name}\" },\n")
        continue()
    endif()
    set(args -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3 -O3 -I "${SRC}/compute" -I "${SRC}")
    if(GFX)
        list(APPEND args -I "${GFX}")
    endif()
    if(kind STREQUAL "shadow")
        list(APPEND args -I "${SHADOW}" -D WXL_LIGHTS_POINT_SHADOWS=1)
    endif()
    set(spv "${WORK}/${name}.spv")
    execute_process(
        COMMAND "${DXC}" ${args} "${hlsl}" -Fo "${spv}"
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "CompileShaders.cmake: dxc failed on ${hlsl} (${name}):\n${out}${err}")
    endif()
    if(out OR err)
        message(STATUS "CompileShaders.cmake: dxc on ${name}:\n${out}${err}")
    endif()

    # The module as little-endian 32-bit words, eight to a line.
    file(READ "${spv}" hex HEX)
    string(LENGTH "${hex}" digits)
    math(EXPR bytes "${digits} / 2")
    math(EXPR rest "${bytes} % 4")
    if(NOT rest EQUAL 0 OR bytes EQUAL 0)
        message(FATAL_ERROR "CompileShaders.cmake: ${spv} is not a SPIR-V module (${bytes} bytes)")
    endif()
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u, " words "${hex}")
    set(w "0x[0-9a-f]+u, ")   # CMake's regex has no {8}: the group is spelt out
    string(REGEX REPLACE "(${w}${w}${w}${w}${w}${w}${w}${w})" "\\1\n            " words "${words}")
    string(REPLACE " \n" "\n" words "${words}")
    string(REGEX REPLACE "[ \n]+$" "" words "${words}")
    math(EXPR count "${bytes} / 4")
    string(APPEND text "        // shaders/compute/${source}.cs.hlsl (${name}): ${count} words\n")
    string(APPEND text "        const uint32_t k_${ident}[] = {\n            ${words}\n        };\n\n")
    string(APPEND modules "            { k_${ident}, sizeof k_${ident}, \"lights.${name}\" },\n")
endforeach()

string(APPEND text "        const Module kModules[] = {\n${modules}        };\n\n")

# The D3D9 shaders and the include they read, as adjacent raw string literals (MSVC caps one literal
# at about 16 KB). Carriage returns are stripped, so the text is the same whatever the line endings.
set(texts "")
foreach(pair IN ITEMS "composite.ps.hlsl|d3d9/composite.ps.hlsl" "resolve.ps.hlsl|d3d9/resolve.ps.hlsl"
                      "wxl/lights/hdr.hlsli|wxl/lights/hdr.hlsli")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 key)
    list(GET parts 1 path)
    string(MAKE_C_IDENTIFIER "${key}" ident)
    set(file "${SRC}/${path}")
    if(NOT EXISTS "${file}")
        message(FATAL_ERROR "CompileShaders.cmake: ${file} is missing")
    endif()
    file(READ "${file}" body)
    string(REPLACE "\r" "" body "${body}")
    string(LENGTH "${body}" len)
    if(len GREATER 60000)
        message(FATAL_ERROR "CompileShaders.cmake: ${file} is ${len} bytes; MSVC allows 65535 in one string literal")
    endif()
    set(lit "")
    set(pos 0)
    while(pos LESS len)
        string(SUBSTRING "${body}" ${pos} 8000 chunk)
        string(APPEND lit "            R\"wxllights(${chunk})wxllights\"\n")
        math(EXPR pos "${pos} + 8000")
    endwhile()
    string(APPEND text "        // shaders/${path}: ${len} bytes\n")
    string(APPEND text "        const char k_${ident}[] =\n${lit}        ;\n\n")
    string(APPEND texts "            { \"${key}\", k_${ident}, sizeof k_${ident} - 1 },\n")
endforeach()
string(APPEND text "        struct TextEntry { const char* name; const char* text; size_t size; };\n")
string(APPEND text "        const TextEntry kTexts[] = {\n${texts}        };\n    }\n\n")

string(APPEND text [=[    const Module& Get(uint32_t pipe)
    {
        static const Module kNone = { nullptr, 0, "lights.none" };
        return pipe < sizeof kModules / sizeof kModules[0] ? kModules[pipe] : kNone;
    }

    uint32_t Count() { return uint32_t(sizeof kModules / sizeof kModules[0]); }

    const char* Text(const char* name, size_t* size)
    {
        for (const TextEntry& t : kTexts)
        {
            if (std::strcmp(t.name, name) != 0) continue;
            if (size) *size = t.size;
            return t.text;
        }
        if (size) *size = 0;
        return nullptr;
    }
}
]=])

set(existing "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" existing)
    string(REPLACE "\r" "" existing "${existing}")
endif()
if(NOT existing STREQUAL text)
    get_filename_component(dir "${OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${dir}")
    file(WRITE "${OUT}" "${text}")
    message(STATUS "CompileShaders.cmake: wrote ${OUT}")
endif()
