# Writes every wxl/**/*.hlsl and *.hlsli under ROOT (the extension's shaders folder) into OUT as
# the table wxl::gfx::shaders::kEmbeddedFiles (src/shaders/Compiler.hpp). Run with cmake -P from
# shared.cmake. OUT is rewritten only when its content changed, so a build after an unrelated
# touch does not recompile the table; the script itself is cheap enough to re-run every build.

if(NOT ROOT OR NOT OUT)
    message(FATAL_ERROR "EmbedFiles.cmake: ROOT and OUT are required")
endif()

file(GLOB_RECURSE files RELATIVE "${ROOT}" "${ROOT}/wxl/*.hlsl" "${ROOT}/wxl/*.hlsli")
list(SORT files)
get_filename_component(header "${ROOT}/../src/shaders/Compiler.hpp" ABSOLUTE)

set(text "// Generated by cmake/EmbedFiles.cmake from shaders/wxl; do not edit.\n")
string(APPEND text "#include \"${header}\"\n\n")
string(APPEND text "namespace wxl::gfx::shaders\n{\n    const EmbeddedFile kEmbeddedFiles[] = {\n")

set(count 0)
foreach(rel IN LISTS files)
    file(READ "${ROOT}/${rel}" body)
    # Checked out with either line ending, the text is the same file: strip the carriage returns
    # so the embedded size is exact and a compile key is the same on every machine.
    string(REPLACE "\r" "" body "${body}")
    string(LENGTH "${body}" len)
    string(APPEND text "        { \"${rel}\",\n")
    # MSVC caps one literal at about 16 KB; adjacent raw literals are joined by the compiler.
    set(pos 0)
    while(pos LESS len)
        string(SUBSTRING "${body}" ${pos} 8000 chunk)
        string(APPEND text "          R\"wxlgfx(${chunk})wxlgfx\"\n")
        math(EXPR pos "${pos} + 8000")
    endwhile()
    if(len EQUAL 0)
        string(APPEND text "          \"\"\n")
    endif()
    string(APPEND text "          , ${len} },\n")
    math(EXPR count "${count} + 1")
endforeach()

if(count EQUAL 0)
    # An empty array is not valid C++; a sentinel the count excludes keeps the build whole.
    string(APPEND text "        { nullptr, nullptr, 0 },\n")
endif()

string(APPEND text "    };\n    const int kEmbeddedFileCount = ${count};\n}\n")

set(existing "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" existing)
    string(REPLACE "\r" "" existing "${existing}")
endif()
if(NOT existing STREQUAL text)
    get_filename_component(dir "${OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${dir}")
    file(WRITE "${OUT}" "${text}")
endif()
