# wxl-graphics-fog: compiles the compute shaders (shaders/<name>.cs.hlsl) to SPIR-V with DXC and writes
# them, with the D3D9 composite's source, into OUT (src/gpu/Spirv.gen.cpp, the implementation of
# src/gpu/Spirv.hpp). Run with cmake -P from shared.cmake:
#   DXC   the DirectX Shader Compiler executable
#   SRC   the shaders folder
#   OUT   the generated .cpp (committed: a build without DXC uses it as is)
#   WORK  scratch folder for the .spv files (optional)
# OUT is rewritten only when its content changed; a shader that fails to compile fails the build.

if(NOT DXC OR NOT SRC OR NOT OUT)
    message(FATAL_ERROR "CompileShaders.cmake: DXC, SRC and OUT are required")
endif()
if(NOT WORK)
    set(WORK "${CMAKE_CURRENT_BINARY_DIR}/wxl-graphics-fog-shaders")
endif()
file(MAKE_DIRECTORY "${WORK}")

# The pipelines in the order of FOG_PIPE_* (shaders/shared.h): the table below is indexed by it.
set(passes noise terrain transport ground velocity advect source occupancy light lamps march combine temporal probe debug wake)

set(text "// Generated by cmake/CompileShaders.cmake from shaders/ (DXC, cs_6_0, -spirv, Vulkan 1.3); do not edit.\n")
string(APPEND text "#include \"Spirv.hpp\"\n\n")
string(APPEND text "namespace wxl::gfx::fog::spirv\n{\n    namespace\n    {\n")

set(modules "")
foreach(pass IN LISTS passes)
    set(hlsl "${SRC}/${pass}.cs.hlsl")
    if(NOT EXISTS "${hlsl}")
        message(FATAL_ERROR "CompileShaders.cmake: ${hlsl} is missing (FOG_PIPE_* lists every pass)")
    endif()
    set(spv "${WORK}/${pass}.spv")
    execute_process(
        COMMAND "${DXC}" -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3 -O3 -I "${SRC}" "${hlsl}" -Fo "${spv}"
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "CompileShaders.cmake: dxc failed on ${hlsl}:\n${out}${err}")
    endif()
    if(out OR err)
        message(STATUS "CompileShaders.cmake: dxc on ${pass}:\n${out}${err}")
    endif()

    # The module as little-endian 32-bit words, eight to a line.
    file(READ "${spv}" hex HEX)
    string(LENGTH "${hex}" digits)
    math(EXPR bytes "${digits} / 2")
    math(EXPR rest "${bytes} % 4")
    if(NOT rest EQUAL 0 OR bytes EQUAL 0)
        message(FATAL_ERROR "CompileShaders.cmake: ${spv} is not a SPIR-V module (${bytes} bytes)")
    endif()
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u, " words "${hex}")
    set(w "0x[0-9a-f]+u, ")   # CMake's regex has no {8}: the group is spelt out
    string(REGEX REPLACE "(${w}${w}${w}${w}${w}${w}${w}${w})" "\\1\n            " words "${words}")
    string(REPLACE " \n" "\n" words "${words}")
    string(REGEX REPLACE "[ \n]+$" "" words "${words}")
    math(EXPR count "${bytes} / 4")
    string(APPEND text "        // shaders/${pass}.cs.hlsl: ${count} words\n")
    string(APPEND text "        const uint32_t k_${pass}[] = {\n            ${words}\n        };\n\n")
    string(APPEND modules "            { k_${pass}, sizeof k_${pass}, \"fog.${pass}\" },\n")
endforeach()

string(APPEND text "        const Module kModules[] = {\n${modules}        };\n\n")

# The composite's source as adjacent raw string literals (MSVC caps one literal at about 16 KB).
# Carriage returns are stripped, so the text is the same whatever the checkout's line endings.
set(apply "${SRC}/apply.ps.hlsl")
if(NOT EXISTS "${apply}")
    message(FATAL_ERROR "CompileShaders.cmake: ${apply} is missing")
endif()
file(READ "${apply}" body)
string(REPLACE "\r" "" body "${body}")
string(LENGTH "${body}" len)
if(len GREATER 60000)
    message(FATAL_ERROR "CompileShaders.cmake: ${apply} is ${len} bytes; MSVC allows 65535 in one string literal")
endif()
set(lit "")
set(pos 0)
while(pos LESS len)
    string(SUBSTRING "${body}" ${pos} 8000 chunk)
    string(APPEND lit "            R\"wxlfog(${chunk})wxlfog\"\n")
    math(EXPR pos "${pos} + 8000")
endwhile()
string(APPEND text "        // shaders/apply.ps.hlsl: ${len} bytes\n")
string(APPEND text "        const char kApply[] =\n${lit}        ;\n    }\n\n")

string(APPEND text [=[    const Module& Get(uint32_t pipe)
    {
        static const Module kNone = { nullptr, 0, "fog.none" };
        return pipe < sizeof kModules / sizeof kModules[0] ? kModules[pipe] : kNone;
    }

    uint32_t Count() { return uint32_t(sizeof kModules / sizeof kModules[0]); }

    const char* ApplySource(size_t* size)
    {
        if (size) *size = sizeof kApply - 1;
        return kApply;
    }
}
]=])

set(existing "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" existing)
    string(REPLACE "\r" "" existing "${existing}")
endif()
if(NOT existing STREQUAL text)
    get_filename_component(dir "${OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${dir}")
    file(WRITE "${OUT}" "${text}")
    message(STATUS "CompileShaders.cmake: wrote ${OUT}")
endif()
