// wxl-graphics-extend: HLSL compiled with d3dcompiler_47, cached in memory and on disk.
// Copyright (C) 2026 WarcraftXL
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include "wxl/GraphicsExtendApi.h"

#include <cstddef>
#include <cstdint>
#include <string>

// "wxl/..." includes are served from the built-in library embedded in the DLL (shaders/wxl/gfx/*.hlsli,
// cmake/EmbedFiles.cmake); every other name goes to the descriptor's include callback. A cache entry
// records every file the program included with a hash of its text, so a hit is re-validated against
// the current sources before it is used. Any thread.
namespace wxl::gfx::shaders
{
    /// The embedded built-in files (generated by cmake/EmbedFiles.cmake).
    struct EmbeddedFile
    {
        const char* path;   // "wxl/gfx/depth.hlsli", forward slashes
        const char* text;
        size_t      size;
    };
    extern const EmbeddedFile kEmbeddedFiles[];
    extern const int kEmbeddedFileCount;

    int   Compile(const WXL_GfxShaderDesc* desc, WXL_ByteSink* out);
    bool  Compile(const WXL_GfxShaderDesc* desc, std::string& bytecode);
    void* CreatePixelShader(void* device, const WXL_GfxShaderDesc* desc);
    void* CreateVertexShader(void* device, const WXL_GfxShaderDesc* desc);
    const char* IncludeFile(const char* name, size_t* size);
    void  ClearCache();

    /// Compiles (cache misses) and hits (memory or disk) this session.
    void Stats(uint32_t& compiled, uint32_t& cached);

    /// For the panel: whether d3dcompiler_47 was found, and the disk cache state in one line.
    const char* Status();
}
