// Every DBC table the 12340 client loads: where its WowClientDB<T> lives, the layout it demands
// of the file, and the stride of the records it builds from it.
// GENERATED by tools/extract_clientdb.py -- do not edit by hand.
// Copyright (C) 2026 WarcraftXL
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include <cstddef>
#include <cstdint>

// INTERNAL to the core. Extensions use wxl::game::clientdb, never this.
//
// The client instantiates one WowClientDB<T> per table -- 241 of them -- from a single template.
// Every instance is therefore the same 0x24-byte object, and every generated Load is the same body
// bar two constants. That uniformity is what lets one accessor serve every table.
namespace wxl::offsets::game::clientdb
{
    // --- the object, identical for all 241 instances ---------------------------------------------
    // Read off WowClientDB<T>::Load and ::LoadRecords, which write every one of these.

    constexpr size_t kOffVTable      = 0x00;
    constexpr size_t kOffLoaded      = 0x04;  ///< set at the end of Load; 0 until then
    constexpr size_t kOffRecordCount = 0x08;
    constexpr size_t kOffMaxId       = 0x0C;  ///< accumulated while reading; -1 before
    constexpr size_t kOffMinId       = 0x10;  ///< accumulated while reading; 0x0FFFFFFF before
    constexpr size_t kOffStringBlock = 0x14;  ///< the file's string table, allocated whole

    /// The records themselves, for an `indexed` table only. Untouched by every other loader.
    constexpr size_t kOffRecordBlock = 0x18;

    /// Records back to back for a plain table; record pointers by ordinal for an `indexed` one.
    constexpr size_t kOffRecords     = 0x1C;

    constexpr size_t kOffRowById     = 0x20;  ///< record pointers, indexed by (id - minId)
    constexpr size_t kObjectSize     = 0x24;

    /// The DBC-compression flag, written by ClientDBInitialize from the `dbCompress` CVar. While it
    /// is set, an `indexed` table holds its records packed and every read expands through the
    /// client's own unpacker. No other loader reads the flag, so no other table is affected.
    constexpr uintptr_t kCompressFlag = 0x00C5DEA0;

    /// One table: its client name, its instance, and the layouts its loader insists on.
    struct TableInfo
    {
        const char* name;
        uintptr_t   instance;
        uint32_t    columns;   ///< exact; Load errors on any other count
        uint32_t    rowSize;   ///< bytes on disk -- NOT always columns * 4, some tables hold bytes
        uint32_t    stride;    ///< bytes per record in memory, the constant compiled into LoadRecords
        uint32_t    idDword;   ///< dword of the record the loader takes min/max and the by-id key from
        bool        indexed;   ///< records live at kOffRecordBlock, pointed at from kOffRecords
    };

    inline constexpr TableInfo kTables[] = {
        { "Achievement",                   0x00AD305C,   62,   248,    56,   0, false },
        { "Achievement_Category",          0x00AD30A4,   20,    80,    16,   0, false },
        { "Achievement_Criteria",          0x00AD3080,   31,   124,    60,   0, false },
        { "AnimationData",                 0x00AD30C8,    8,    32,    32,   0, false },
        { "AreaGroup",                     0x00AD30EC,    8,    32,    32,   0, false },
        { "AreaPOI",                       0x00AD3110,   54,   216,    88,   0, false },
        { "AreaTable",                     0x00AD3134,   36,   144,    80,   0, false },
        { "AreaTrigger",                   0x00AD3158,   10,    40,    40,   0, false },
        { "AttackAnimKits",                0x00AD317C,    5,    20,    20,   0, false },
        { "AttackAnimTypes",               0x00AD31A0,    2,     8,     8,   0, false },
        { "AuctionHouse",                  0x00AD31C4,   21,    84,    20,   0, false },
        { "BankBagSlotPrices",             0x00AD31E8,    2,     8,     8,   0, false },
        { "BannedAddOns",                  0x00AD320C,   11,    44,    44,   0, false },
        { "BarberShopStyle",               0x00AD3230,   40,   160,    32,   0, false },
        { "BattlemasterList",              0x00AD3254,   32,   128,    64,   0, false },
        { "CameraShakes",                  0x00AD3278,    8,    32,    32,   0, false },
        { "Cfg_Categories",                0x00AD329C,   21,    84,    20,   0, false },
        { "Cfg_Configs",                   0x00AD32C0,    4,    16,    20,   4, false },
        { "CharBaseInfo",                  0x00AD32E4,    2,     2,     8,   1, false },
        { "CharHairGeosets",               0x00AD3308,    6,    24,    24,   0, false },
        { "CharSections",                  0x00AD332C,   10,    40,    40,   0, false },
        { "CharStartOutfit",               0x00AD3350,   77,   296,   296,   0, false },
        { "CharTitles",                    0x00AD3374,   37,   148,    20,   0, false },
        { "CharacterFacialHairStyles",     0x00AD3398,    8,    32,    36,   8, false },
        { "ChatChannels",                  0x00AD33BC,   37,   148,    20,   0, false },
        { "ChatProfanity",                 0x00AD33E0,    3,    12,    12,   0, false },
        { "ChrClasses",                    0x00AD3404,   60,   240,    48,   0, false },
        { "ChrRaces",                      0x00AD3428,   69,   276,    84,   0, false },
        { "CinematicCamera",               0x00AD344C,    7,    28,    28,   0, false },
        { "CinematicSequences",            0x00AD3470,   10,    40,    40,   0, false },
        { "CreatureDisplayInfo",           0x00AD34B8,   16,    64,    64,   0, false },
        { "CreatureDisplayInfoExtra",      0x00AD3494,   21,    84,    84,   0, false },
        { "CreatureFamily",                0x00AD34DC,   28,   112,    48,   0, false },
        { "CreatureModelData",             0x00AD3500,   28,   112,   112,   0, false },
        { "CreatureMovementInfo",          0x00AD3524,    2,     8,     8,   0, false },
        { "CreatureSoundData",             0x00AD3548,   38,   152,   152,   0, false },
        { "CreatureSpellData",             0x00AD356C,    9,    36,    36,   0, false },
        { "CreatureType",                  0x00AD3590,   19,    76,    12,   0, false },
        { "CurrencyCategory",              0x00AD35D8,   19,    76,    12,   0, false },
        { "CurrencyTypes",                 0x00AD35B4,    4,    16,    16,   0, false },
        { "DanceMoves",                    0x00AD35FC,   24,    96,    32,   0, false },
        { "DeathThudLookups",              0x00AD3620,    5,    20,    20,   0, false },
        { "DeclinedWord",                  0x00AD3644,    2,     8,     8,   0, false },
        { "DeclinedWordCases",             0x00AD3668,    4,    16,    16,   0, false },
        { "DestructibleModelData",         0x00AD368C,   19,    76,    76,   0, false },
        { "DungeonEncounter",              0x00AD36B0,   23,    92,    28,   0, false },
        { "DungeonMap",                    0x00AD36D4,    8,    32,    32,   0, false },
        { "DungeonMapChunk",               0x00AD36F8,    5,    20,    20,   0, false },
        { "DurabilityCosts",               0x00AD371C,   30,   120,   120,   0, false },
        { "DurabilityQuality",             0x00AD3740,    2,     8,     8,   0, false },
        { "Emotes",                        0x00AD3764,    7,    28,    28,   0, false },
        { "EmotesText",                    0x00AD37D0,   19,    76,    76,   0, false },
        { "EmotesTextData",                0x00AD3788,   18,    72,     8,   0, false },
        { "EmotesTextSound",               0x00AD37AC,    5,    20,    20,   0, false },
        { "EnvironmentalDamage",           0x00AD37F4,    3,    12,    12,   0, false },
        { "Exhaustion",                    0x00AD3818,   23,    92,    28,   0, false },
        { "Faction",                       0x00AD3860,   57,   228,   100,   0, false },
        { "FactionGroup",                  0x00AD383C,   20,    80,    16,   0, false },
        { "FactionTemplate",               0x00AD3884,   14,    56,    56,   0, false },
        { "FileData",                      0x00AD38A8,    3,    12,    12,   0, false },
        { "FootprintTextures",             0x00AD38CC,    2,     8,     8,   0, false },
        { "FootstepTerrainLookup",         0x00AD38F0,    5,    20,    20,   0, false },
        { "GMSurveyAnswers",               0x00AD3A10,   20,    80,    16,   0, false },
        { "GMSurveyCurrentSurvey",         0x00AD3A34,    2,     8,     8,   0, false },
        { "GMSurveyQuestions",             0x00AD3A58,   18,    72,     8,   0, false },
        { "GMSurveySurveys",               0x00AD3A7C,   11,    44,    44,   0, false },
        { "GMTicketCategory",              0x00AD3AA0,   18,    72,     8,   0, false },
        { "GameObjectArtKit",              0x00AD3914,    8,    32,    32,   0, false },
        { "GameObjectDisplayInfo",         0x00AD3938,   19,    76,    76,   0, false },
        { "GameTables",                    0x00AD395C,    3,    12,    16,   3, false },
        { "GameTips",                      0x00AD3980,   18,    72,     8,   0, false },
        { "GemProperties",                 0x00AD39A4,    5,    20,    20,   0, false },
        { "GlyphProperties",               0x00AD39C8,    4,    16,    16,   0, false },
        { "GlyphSlot",                     0x00AD39EC,    3,    12,    12,   0, false },
        { "GroundEffectDoodad",            0x00AD3AC4,    3,    12,    12,   0, false },
        { "GroundEffectTexture",           0x00AD3AE8,   11,    44,    44,   0, false },
        { "HelmetGeosetVisData",           0x00AD3CBC,    8,    32,    32,   0, false },
        { "HolidayDescriptions",           0x00AD3CE0,   18,    72,     8,   0, false },
        { "HolidayNames",                  0x00AD3D04,   18,    72,     8,   0, false },
        { "Holidays",                      0x00AD3D28,   55,   220,   220,   0, false },
        { "Item",                          0x00AD3D4C,    8,    32,    32,   0, false },
        { "ItemBagFamily",                 0x00AD3D70,   18,    72,     8,   0, false },
        { "ItemClass",                     0x00AD3D94,   20,    80,    20,   4, false },
        { "ItemCondExtCosts",              0x00AD3DB8,    4,    16,    16,   0, false },
        { "ItemDisplayInfo",               0x00AD3DDC,   25,   100,   100,   0, true  },
        { "ItemExtendedCost",              0x00AD3E00,   16,    64,    64,   0, false },
        { "ItemGroupSounds",               0x00AD3E24,    5,    20,    20,   0, false },
        { "ItemLimitCategory",             0x00AD3E48,   20,    80,    16,   0, false },
        { "ItemPetFood",                   0x00AD3E6C,   18,    72,     8,   0, false },
        { "ItemPurchaseGroup",             0x00AD3E90,   26,   104,    40,   0, false },
        { "ItemRandomProperties",          0x00AD3EB4,   24,    96,    32,   0, false },
        { "ItemRandomSuffix",              0x00AD3ED8,   29,   116,    52,   0, false },
        { "ItemSet",                       0x00AD3EFC,   53,   212,   148,   0, false },
        { "ItemSubClass",                  0x00AD3F44,   44,   176,    52,  12, false },
        { "ItemSubClassMask",              0x00AD3F20,   19,    76,    16,   3, false },
        { "ItemVisualEffects",             0x00AD3F68,    2,     8,     8,   0, false },
        { "ItemVisuals",                   0x00AD3F8C,    6,    24,    24,   0, false },
        { "LanguageWords",                 0x00AD3FB0,    3,    12,    12,   0, false },
        { "Languages",                     0x00AD3FD4,   18,    72,     8,   0, false },
        { "LfgDungeonExpansion",           0x00AD3FF8,    8,    32,    32,   0, false },
        { "LfgDungeonGroup",               0x00AD401C,   21,    84,    20,   0, false },
        { "LfgDungeons",                   0x00AD4040,   49,   196,    68,   0, false },
        { "Light",                         0x00AF4A28,   15,    60,    60,   0, false },
        { "LightFloatBand",                0x00AF49E0,   34,   136,   136,   0, true  },
        { "LightIntBand",                  0x00AF49BC,   34,   136,   136,   0, true  },
        { "LightParams",                   0x00AF4A04,    9,    36,    36,   0, false },
        { "LightSkybox",                   0x00AF4998,    3,    12,    12,   0, false },
        { "LiquidMaterial",                0x00AD4088,    3,    12,    12,   0, false },
        { "LiquidType",                    0x00AD4064,   45,   180,   180,   0, false },
        { "LoadingScreenTaxiSplines",      0x00AD40D0,   19,    76,    76,   0, false },
        { "LoadingScreens",                0x00AD40AC,    4,    16,    16,   0, false },
        { "Lock",                          0x00AD40F4,   33,   132,   132,   0, false },
        { "LockType",                      0x00AD4118,   53,   212,    20,   0, false },
        { "MailTemplate",                  0x00AD413C,   35,   140,    12,   0, false },
        { "Map",                           0x00AD4160,   66,   264,    72,   0, false },
        { "MapDifficulty",                 0x00AD4184,   23,    92,    28,   0, false },
        { "Material",                      0x00AD41A8,    5,    20,    20,   0, false },
        { "Movie",                         0x00AD41CC,    3,    12,    12,   0, false },
        { "MovieFileData",                 0x00AD41F0,    2,     8,     8,   0, false },
        { "MovieVariation",                0x00AD4214,    3,    12,    12,   0, false },
        { "NPCSounds",                     0x00AD425C,    5,    20,    20,   0, false },
        { "NameGen",                       0x00AD4238,    4,    16,    16,   0, false },
        { "NamesProfanity",                0x00AD4280,    3,    12,    12,   0, false },
        { "NamesReserved",                 0x00AD42A4,    3,    12,    12,   0, false },
        { "ObjectEffect",                  0x00AD5048,   12,    48,    48,   0, false },
        { "ObjectEffectGroup",             0x00AD506C,    2,     8,     8,   0, false },
        { "ObjectEffectModifier",          0x00AD5090,    8,    32,    32,   0, false },
        { "ObjectEffectPackage",           0x00AD50B4,    2,     8,     8,   0, false },
        { "ObjectEffectPackageElem",       0x00AD50D8,    4,    16,    16,   0, false },
        { "OverrideSpellData",             0x00AD42C8,   12,    48,    48,   0, false },
        { "Package",                       0x00AD42EC,   20,    80,    16,   0, false },
        { "PageTextMaterial",              0x00AD4310,    2,     8,     8,   0, false },
        { "PaperDollItemFrame",            0x00AD4334,    3,    12,    16,   3, false },
        { "ParticleColor",                 0x00AD4358,   10,    40,    40,   0, false },
        { "PetPersonality",                0x00AD437C,   24,    96,    32,   0, false },
        { "PowerDisplay",                  0x00AD43A0,    6,    15,    16,   0, false },
        { "PvpDifficulty",                 0x00AD43C4,    6,    24,    24,   0, false },
        { "QuestFactionReward",            0x00AD43E8,   11,    44,    44,   0, false },
        { "QuestInfo",                     0x00AD440C,   18,    72,     8,   0, false },
        { "QuestSort",                     0x00AD4430,   18,    72,     8,   0, false },
        { "QuestXP",                       0x00AD4454,   11,    44,    44,   0, false },
        { "RandPropPoints",                0x00AD449C,   16,    64,    64,   0, false },
        { "Resistances",                   0x00AD4478,   20,    80,    16,   0, false },
        { "ScalingStatDistribution",       0x00AD44C0,   22,    88,    88,   0, false },
        { "ScalingStatValues",             0x00AD44E4,   24,    96,    96,   0, false },
        { "ScreenEffect",                  0x00AD4508,   10,    40,    40,   0, false },
        { "ServerMessages",                0x00AD452C,   18,    72,     8,   0, false },
        { "SheatheSoundLookups",           0x00AD4550,    7,    28,    28,   0, false },
        { "SkillCostsData",                0x00AD4574,    5,    20,    20,   0, false },
        { "SkillLine",                     0x00AD45E0,   56,   224,    32,   0, false },
        { "SkillLineAbility",              0x00AD4598,   14,    56,    56,   0, false },
        { "SkillLineCategory",             0x00AD45BC,   19,    76,    12,   0, false },
        { "SkillRaceClassInfo",            0x00AD4604,    8,    32,    32,   0, false },
        { "SkillTiers",                    0x00AD4628,   33,   132,   132,   0, false },
        { "SoundAmbience",                 0x00AD464C,    3,    12,    12,   0, false },
        { "SoundEmitters",                 0x00AD4694,   10,    40,    40,   0, false },
        { "SoundEntries",                  0x00AD4670,   30,   120,   120,   0, false },
        { "SoundEntriesAdvanced",          0x00AD5024,   24,    96,    96,   0, false },
        { "SoundFilter",                   0x00AD50FC,    2,     8,     8,   0, false },
        { "SoundFilterElem",               0x00AD5120,   13,    52,    52,   0, false },
        { "SoundProviderPreferences",      0x00AD46B8,   24,    96,    96,   0, false },
        { "SoundSamplePreferences",        0x00AD46DC,   17,    68,    68,   0, false },
        { "SoundWaterType",                0x00AD4700,    4,    16,    16,   0, false },
        { "SpamMessages",                  0x00AD4724,    2,     8,     8,   0, false },
        { "Spell",                         0x00AD49D0,  234,   936,   680,   0, true  },
        { "SpellCastTimes",                0x00AD4748,    4,    16,    16,   0, false },
        { "SpellCategory",                 0x00AD476C,    2,     8,     8,   0, false },
        { "SpellChainEffects",             0x00AD4790,   48,   177,   180,   0, false },
        { "SpellDescriptionVariables",     0x00AD47B4,    2,     8,     8,   0, false },
        { "SpellDifficulty",               0x00AD47D8,    5,    20,    20,   0, false },
        { "SpellDispelType",               0x00AD47FC,   21,    84,    20,   0, false },
        { "SpellDuration",                 0x00AD4820,    4,    16,    16,   0, false },
        { "SpellEffectCameraShakes",       0x00AD4844,    4,    16,    16,   0, false },
        { "SpellFocusObject",              0x00AD4868,   18,    72,     8,   0, false },
        { "SpellIcon",                     0x00AD488C,    2,     8,     8,   0, false },
        { "SpellItemEnchantment",          0x00AD48B0,   38,   152,    88,   0, false },
        { "SpellItemEnchantmentCondition", 0x00AD48D4,   31,    64,    72,   0, false },
        { "SpellMechanic",                 0x00AD48F8,   18,    72,     8,   0, false },
        { "SpellMissile",                  0x00AD491C,   15,    60,    60,   0, false },
        { "SpellMissileMotion",            0x00AD4940,    5,    20,    20,   0, false },
        { "SpellRadius",                   0x00AD4964,    4,    16,    16,   0, false },
        { "SpellRange",                    0x00AD4988,   40,   160,    32,   0, false },
        { "SpellRuneCost",                 0x00AD49AC,    5,    20,    20,   0, false },
        { "SpellShapeshiftForm",           0x00AD49F4,   35,   140,    76,   0, false },
        { "SpellVisual",                   0x00AD4AA8,   32,   128,   128,   0, false },
        { "SpellVisualEffectName",         0x00AD4A18,    7,    28,    28,   0, false },
        { "SpellVisualKit",                0x00AD4A3C,   38,   152,   152,   0, false },
        { "SpellVisualKitAreaModel",       0x00AD4A60,    3,    12,    12,   0, false },
        { "SpellVisualKitModelAttach",     0x00AD4A84,   10,    40,    40,   0, false },
        { "StableSlotPrices",              0x00AD4ACC,    2,     8,     8,   0, false },
        { "Startup_Strings",               0x00AB6350,   19,    76,    12,   0, false },
        { "Stationery",                    0x00AD4AF0,    4,    16,    16,   0, false },
        { "StringLookups",                 0x00AD4B14,    2,     8,     8,   0, false },
        { "SummonProperties",              0x00AD4B38,    6,    24,    24,   0, false },
        { "Talent",                        0x00AD4B5C,   23,    92,    92,   0, false },
        { "TalentTab",                     0x00AD4B80,   24,    96,    32,   0, false },
        { "TaxiNodes",                     0x00AD4BA4,   24,    96,    32,   0, false },
        { "TaxiPath",                      0x00AD4BEC,    4,    16,    16,   0, false },
        { "TaxiPathNode",                  0x00AD4BC8,   11,    44,    44,   0, false },
        { "TeamContributionPoints",        0x00AD4C10,    2,     8,     8,   0, false },
        { "TerrainType",                   0x00AD4C34,    6,    24,    28,   6, false },
        { "TerrainTypeSounds",             0x00AD4C58,    1,     4,     4,   0, false },
        { "TotemCategory",                 0x00AD4C7C,   20,    80,    16,   0, false },
        { "TransportAnimation",            0x00AD4CA0,    7,    28,    28,   0, false },
        { "TransportPhysics",              0x00AD4CC4,   11,    44,    44,   0, false },
        { "TransportRotation",             0x00AD4CE8,    7,    28,    28,   0, false },
        { "UISoundLookups",                0x00AD4D0C,    3,    12,    12,   0, false },
        { "UnitBlood",                     0x00AD4D54,   10,    40,    40,   0, false },
        { "UnitBloodLevels",               0x00AD4D30,    4,    16,    16,   0, false },
        { "Vehicle",                       0x00AD4D78,   40,   160,   160,   0, false },
        { "VehicleSeat",                   0x00AD4D9C,   58,   232,   232,   0, false },
        { "VehicleUIIndSeat",              0x00AD4DE4,    5,    20,    20,   0, false },
        { "VehicleUIIndicator",            0x00AD4DC0,    2,     8,     8,   0, false },
        { "VideoHardware",                 0x00ADBF88,   23,    92,    92,   0, false },
        { "VocalUISounds",                 0x00AD4E08,    7,    28,    28,   0, false },
        { "WMOAreaTable",                  0x00AD4E2C,   28,   112,    48,   0, false },
        { "WeaponImpactSounds",            0x00AD4E50,   23,    92,    92,   0, false },
        { "WeaponSwingSounds2",            0x00AD4E74,    4,    16,    16,   0, false },
        { "Weather",                       0x00AD4E98,    8,    32,    32,   0, false },
        { "WorldChunkSounds",              0x00AD5000,    9,    36,    40,   9, false },
        { "WorldMapArea",                  0x00AD4EBC,   11,    44,    44,   0, false },
        { "WorldMapContinent",             0x00AD4EE0,   14,    56,    56,   0, false },
        { "WorldMapOverlay",               0x00AD4F04,   17,    68,    68,   0, false },
        { "WorldMapTransforms",            0x00AD4F28,   10,    40,    40,   0, false },
        { "WorldSafeLocs",                 0x00AD4F4C,   22,    88,    24,   0, false },
        { "WorldStateUI",                  0x00AD4F70,   63,   252,    60,   0, false },
        { "WorldStateZoneSounds",          0x00AD4FDC,    8,    32,    36,   8, false },
        { "ZoneIntroMusicTable",           0x00AD4F94,    5,    20,    20,   0, false },
        { "ZoneMusic",                     0x00AD4FB8,    8,    32,    32,   0, false },
        { "gtBarberShopCostBase",          0x00AD3B0C,    1,     4,     8,   1, false },
        { "gtChanceToMeleeCrit",           0x00AD3B54,    1,     4,     8,   1, false },
        { "gtChanceToMeleeCritBase",       0x00AD3B78,    1,     4,     8,   1, false },
        { "gtChanceToSpellCrit",           0x00AD3B9C,    1,     4,     8,   1, false },
        { "gtChanceToSpellCritBase",       0x00AD3BC0,    1,     4,     8,   1, false },
        { "gtCombatRatings",               0x00AD3B30,    1,     4,     8,   1, false },
        { "gtNPCManaCostScaler",           0x00AD3BE4,    1,     4,     8,   1, false },
        { "gtOCTClassCombatRatingScalar",  0x00AD3C08,    2,     8,     8,   0, false },
        { "gtOCTRegenHP",                  0x00AD3C2C,    1,     4,     8,   1, false },
        { "gtOCTRegenMP",                  0x00AD3C50,    1,     4,     8,   1, false },
        { "gtRegenHPPerSpt",               0x00AD3C74,    1,     4,     8,   1, false },
        { "gtRegenMPPerSpt",               0x00AD3C98,    1,     4,     8,   1, false },
    };

    inline constexpr size_t kTableCount = sizeof(kTables) / sizeof(kTables[0]);
}
